---
linters:
  enable:
    - asasalint
    - bodyclose
    - contextcheck
    - copyloopvar
    - depguard
    - durationcheck
    - errcheck 
    - errname
    - errorlint
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - unparam
    - usestdlibvars
    - wastedassign
linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        allow: [aireone.xyz/labtime] # It's mendatory to have at least one package in allow or deny list
  errcheck:
    check-type-assertions: true 
    check-blank: true
