---
version: "2"
linters:
  enable:
    - asasalint
    - bodyclose
    - contextcheck
    - copyloopvar
    - depguard
    - durationcheck
    - errname
    - errorlint
    - gocritic
    - godot
    - gosec
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - aireone.xyz/labtime
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
