{
 "title": "Labtime",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Sites Status Code",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "labtime_http_site_status_code", "legendFormat": "{{http_monitor_site_name}}" }
   ]
  },
  {
   "title": "TLS Certificate Remaining Days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "labtime_tls_cert_expire_time", "legendFormat": "{{tls_monitor_name}}" }
   ]
  },
  {
   "title": "Docker Containers Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "labtime_docker_container_status",
     "legendFormat": "{{docker_monitor_name}}"
    }
   ]
  }
 ]
}