---
targets:
  - name: Home
    url: https://aireone.xyz
    interval: 20
  - name: Gitea
    url: https://gitea.aireone.xyz
    interval: 60
tls_monitors:
  - domain: aireone.xyz
  - domain: gitea.aireone.xyz
