---
# yaml-language-server: $schema=../labtime-configuration-schema.json
http_status_code:
  - url: https://aireone.xyz
  - url: https://gitea.aireone.xyz
tls_monitors:
  - domain: aireone.xyz
  - domain: gitea.aireone.xyz
docker_monitors:
  - container_name: example-stack-grafana-1
  - name: prom
    container_name: example-stack-prometheus-1
