---
when:
  event: pull_request

steps:
  golang:
    image: golang:1.25.0
    commands:
      - go test -v ./...
    depends_on: []

  tidy:
    image: golang:1.25.0
    commands:
      - go mod tidy -diff
    depends_on: []

  deadcode:
    image: golang:1.25.0
    commands:
      - go install golang.org/x/tools/cmd/deadcode@latest
      - |
        OUTPUT=$(deadcode -test ./...)
        if [ -n "$OUTPUT" ]; then
          echo "$OUTPUT"
          exit 1
        fi
    depends_on: []

  "generate yaml schema":
    image: golang:1.25.0
    commands:
      - mv
        labtime-configuration-schema.json
        /tmp/labtime-configuration-schema.json
      - go generate ./cmd/generator/main.go
      - diff
        --brief
        /tmp/labtime-configuration-schema.json
        labtime-configuration-schema.json
    depends_on: []
